version: "3.7"
services:
 rails:
  image: jamesattree/rails:new
  volumes:
   - ./app/:/app
  ports:
   - "3000:3000"
  depends_on:
   - "mysql-server"

 mysql-server:
  image: mysql:8.0.19
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
   - ./mysql-data/:/var/lib/mysql
  ports:
   - 3306:3306
  command: mysqld --default-authentication-plugin=mysql_native_password

 phpmyadmin:
  image: phpmyadmin/phpmyadmin:5.0.1
  restart: always
  environment:
   PMA_HOST: mysql-server
   PMA_USER: root
   PMA_PASSWORD: root
  ports:
   - "5000:80"

volumes:
 mysql-data:
